application: egypt-election-2012-demo-gadget
version: eg2012
runtime: python
api_version: 1

default_expiration: "2m"

handlers:
# Visit /results-map.html to serve statically
- url: /(.*)
  static_files: static/\1
  upload: static/(.*)
  
- url: /(.*)
  static_files: static/\1
  upload: static/(.*)

# Visit /results/embed to run results-app.py 
# - url: /(results/vote-data|results/embed)
  # script: results-app.py
#   
# - url: /results/(css/.*|images/.*|js/.*|locale/.*|shapes/.*)
  # static_files: static/\1
  # upload: static/(css/.*|images/.*|js/.*|locale/.*|shapes/.*)
