application: egypt-election-2012-demo
version: eg-geojson
runtime: python27
threadsafe: no
api_version: 1

default_expiration: "2m"

handlers:

- url: /(results/vote-data|results/embed)
  script: results-app.py
  
- url: /results/(css/.*|images/.*|js/.*|locale/.*|shapes/.*)
  static_files: static/\1
  upload: static/(css/.*|images/.*|js/.*|locale/.*|shapes/.*)
